POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json


{
  "username": "ansul",
  "email": "ansul@gmail.com",
  "password": "bht",
  "name": "pahul"
}

### Example Request 
POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json


{
  "email": "ansul@gmail.com",
  "password": "bht"
}

###
POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json


{
  "email": "ansul@gmail.com",
  "password": "bht"
}


###
POST http://localhost:9090/get_user_and_profile HTTP/1.1
Content-Type: application/json

{
  "token" :  "e32510c791f2dd75232ab6707322a1179196ceefa45d7da7bd1b3fc0c7f39035"
}

###
POST http://localhost:9090/update_profile_data HTTP/1.1
Content-Type: application/json

{
  "token":  "e32510c791f2dd75232ab6707322a1179196ceefa45d7da7bd1b3fc0c7f39035",
  "bio"
  "currentPost"
  "pastwork": [
    {
      "company": "Microsoft",
      "position": "CTO",
      "years": "2+"
    }
  ],
  "education": [
    {
      "school": "IIT",
      "degree": "B.Tech",
      "fieldOfStudy": "2015-2019",
    }
  ]
}

###
GET http://localhost:9090/user/get_all_users HTTP/1.1
Content-Type: application/json

{
  "token":
   "e32510c791f2dd75232ab6707322a1179196ceefa45d7da7bd1b3fc0c7f39035"
}
