POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json


{
  "username": "anshul",
  "email": "anshul@gmail.com",
  "password": "bht",
  "name": "pahul"
}

### Example Request 
POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json


{
  "email": "anshul@gmail.com",
  "password": "bht"
}

###
POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json


{
  "email": "anshul@gmail.com",
  "password": "bht"
}


###
POST http://localhost:9090/get_user_and_profile HTTP/1.1
Content-Type: application/json

{
  "token" :  "5922367d44c1fd9aa55a9c5a18b7a403b124ac4a07825baa8e39c179b919d4fe"
}

###
POST http://localhost:9090/update_profile_data HTTP/1.1
Content-Type: application/json

{
  "token":  "5922367d44c1fd9aa55a9c5a18b7a403b124ac4a07825baa8e39c179b919d4fe",
  "bio"
  "currentPost"
  "pastwork": [
    {
      "company": "Microsoft",
      "position": "CTO",
      "years": "2+"
    }
  ],
  "education": [
    {
      "school": "IIT",
      "degree": "B.Tech",
      "fieldOfStudy": "2015-2019",
    }
  ]
}

###
GET http://localhost:9090/user/get_all_users HTTP/1.1
Content-Type: application/json

{
  "token":
   "5922367d44c1fd9aa55a9c5a18b7a403b124ac4a07825baa8e39c179b919d4fe"
}
